### ISSUE TITLE
git install error

### ISSUE THREAD

**Issue by jocelynguo** [ravidziv/IDNNs#17]
I like to use pip3 install with the syntax:
pip3 install git+https://github.com/ravidziv/IDNNs.git

I got this error message:
Collecting git+https://github.com/ravidziv/IDNNs.git
  Cloning https://github.com/ravidziv/IDNNs.git to /private/tmp/pip-req-build-59as3hdr
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/anaconda3/lib/python3.6/tokenize.py", line 452, in open
        buffer = _builtin_open(filename, 'rb')
    FileNotFoundError: [Errno 2] No such file or directory: '/private/tmp/pip-req-build-59as3hdr/setup.py'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/tmp/pip-req-build-59as3hdr/

Anyone knows how to solve it? I am using MacOS, and I also try this syntax in another Mac which also gives me the same error.

**Comment by Xu1yuan2** [comment]
me too
